clear all
load('StressVsCycles.mat')
%plotting stress_strain (using Sample 52 as an example)
plot(Stress_Strain_Asc(:,1),Stress_Strain_Asc(:,2),'-r',...
    Stress_Strain_Asc(:,1),Stress_Strain_Asc(:,3),'-.r',...
    Stress_Strain_Asc(:,1),Stress_Strain_Asc(:,4),'--r',...
    Stress_Strain_Desc(:,1),Stress_Strain_Desc(:,2),'-k',...
    Stress_Strain_Desc(:,1),Stress_Strain_Desc(:,3),'-.k',...
    Stress_Strain_Desc(:,1),Stress_Strain_Desc(:,4),'--k','LineWidth',1.5)

set(gca,'FontName','Times New Roman','FontSize',12)
ylabel('Stress (MPa)','FontWeight','bold','FontName','Times New Roman','FontSize',14)
xlabel('Strain (%)','FontWeight','bold','FontName','Times New Roman','FontSize',14)
%xticks(0:2:20);
grid on
legend('0.1 %/min - Asc', '1 %/min - Asc','10 %/min - Asc',...
    '0.1 %/min - Desc', '1 %/min - Desc','10 %/min - Desc',...
    'FontName','Times New Roman','FontSize',14)